### ISSUE TITLE
Add ability to preview only a single or a few fonts

### ISSUE THREAD

**Issue by bew** [eyeplum/cicero-tui#2]
Hello, very nice tool!

Would it be possible to add the ability to select only one or a few fonts for preview?

For example for my editor I'm choosing which fonts to use for which chars, and would like to see how a specific font renders some chars.

---
Another thing that would be _really_ cool is to preview ligatures, and their various font features.

**Comment by eyeplum** [comment]
Hi @bew,

Selecting specific fonts is definitely a feature we could add! I was actually considering adding a launch argument (or a config file option) for this (in order to solve the issue of not being able to use `fontconfig` on Windows).

As for ligatures, this is also something on the back of my mind. At the moment it's only using `freetype` to render the characters with a given font (a one to one mapping from a character to a glyph in a font). If I understand it correctly, a ligature is likely to require a `n` to one mapping from a number of characters to a glyph which I think would require libraries such as `harfbuzz`. This is certainly something we could investigate and I agree it would be _really_ cool!

I will try to find some time to refine the ideas I have in mind and start work on them. If you are interested in give it a go please also feel free :)

**Comment by eyeplum** [comment]
Hey @bew ,

I've just released `0.2.0` adding support for configuring fonts in character previews (see [the new section in README.md](https://github.com/eyeplum/cicero-tui#configuration) for more details).

Please let me know what you think :)

**Comment by bew** [comment]
Hello @eyeplum! Looks good!

Do you plan to add command line options to not have to edit the config file anytime I want to test something different?

**Comment by eyeplum** [comment]
Hey @bew ,

That certainly can be done :)

Do you think something like this would work?
```
$ cicero -t --override-preview-fonts="CJK","Noto Sans" # Overrides the preview font entries in settings.toml,
                                                       # still matching fonts in the search paths with the same rule.
                                                       # Maybe also a sort form of -p?
```
I get a feeling maybe we should omit the code point range in the command line interface, otherwise it may become a bit too verbose.

**Comment by bew** [comment]
I'm thinking of less verbose args, and I think it's not a problem to have many cli arguments if we want:

`cicero -t --fonts-match=foo,bar --codepoints 0x0042..0x0046`

I think `--override-preview-fonts` is too long, and the fact that it overrides something is implied (and can be documente it) by the fact that you're explicitly passing it on cli.
And I'm using `match` to show it's not a font name but a partial name.

For codepoints I think it's ok, we're showing a specific font for these codepoints.

To match with the available config options, there can be `--no-fontconfig` and `--font-search-path /path/`
